/** Menú principal espejo de oneclickstore.com */
export type NavChild = { label: string; href: string };
export type NavItem = { label: string; href: string; children?: NavChild[] };

export const MAIN_NAV: NavItem[] = [
  {
    label: "Mac",
    href: "/mac",
    children: [
      { label: "Shop Mac →", href: "/mac" },
      { label: "Nuevas MacBook Neo", href: "/mac/macbook-neo" },
      { label: "Nuevas MacBook Air", href: "/mac/macbook-air" },
      { label: "Nuevas MacBook Pro", href: "/mac/macbook-pro" },
      { label: "iMac", href: "/mac/imac" },
      { label: "Mac mini", href: "/mac/mac-mini" },
      { label: "Mac Studio →", href: "/mac/mac-studio" },
      { label: "Displays →", href: "/mac/studio-display" },
      { label: "Accesorios →", href: "/accesorios" },
    ],
  },
  {
    label: "iPhone",
    href: "/iphone",
    children: [
      { label: "Shop iPhone →", href: "/iphone" },
      { label: "Nuevos iPhone 17 Pro", href: "/iphone/iphone-17-pro" },
      { label: "Nuevos iPhone Air", href: "/iphone/iphone-air" },
      { label: "Nuevos iPhone 17", href: "/iphone/iphone-17" },
      { label: "iPhone 17e", href: "/iphone/iphone-17e" },
      { label: "iPhone 16", href: "/iphone/iphone-16" },
      { label: "iPhone 15", href: "/iphone/iphone-15" },
      { label: "Cargadores →", href: "/accesorios/cargadores" },
      { label: "Accesorios →", href: "/accesorios" },
    ],
  },
  {
    label: "iPad",
    href: "/ipad",
    children: [
      { label: "Shop iPad →", href: "/ipad" },
      { label: "Nuevos iPad Pro", href: "/ipad/ipad-pro" },
      { label: "Nuevos iPad Air", href: "/ipad/ipad-air" },
      { label: "iPad mini", href: "/ipad/ipad-mini" },
      { label: "iPad", href: "/ipad/ipad-gen" },
      { label: "Teclado, mouse y pencil →", href: "/accesorios/teclados-mouse-y-pencil" },
      { label: "Accesorios →", href: "/accesorios" },
    ],
  },
  {
    label: "AirPods",
    href: "/airpods",
    children: [
      { label: "Shop AirPods →", href: "/airpods" },
      { label: "Nuevos AirPods Max", href: "/airpods/airpods-max" },
      { label: "Nuevos AirPods Pro 3", href: "/airpods/airpods-pro" },
      { label: "AirPods Pro 2", href: "/airpods/airpods-pro" },
      { label: "AirPods 4", href: "/airpods/airpods-airpods" },
      { label: "Fundas y Cobertores →", href: "/accesorios/fundas-y-cobertores" },
      { label: "Accesorios →", href: "/accesorios" },
    ],
  },
  {
    label: "Apple Watch",
    href: "/watch",
    children: [
      { label: "Shop Apple Watch →", href: "/watch" },
      { label: "Nuevos Apple Watch Series", href: "/watch/watch-series" },
      { label: "Nuevos Apple Watch SE", href: "/watch/watch-se" },
      { label: "Nuevos Apple Watch Ultra", href: "/watch/watch-ultra" },
      { label: "Correa Apple Watch →", href: "/accesorios/correa-apple-watch" },
      { label: "Accesorios →", href: "/accesorios" },
    ],
  },
  { label: "Apple TV", href: "/apple-tv" },
  {
    label: "Audio",
    href: "/audio",
    children: [
      { label: "Shop Audio →", href: "/audio" },
      { label: "JBL Auriculares", href: "/audio/auriculares" },
      { label: "JBL Parlantes", href: "/audio/parlantes" },
    ],
  },
  {
    label: "Accesorios",
    href: "/accesorios",
    children: [
      { label: "AirTag", href: "/accesorios/airtag" },
      { label: "Cargadores", href: "/accesorios/cargadores" },
      { label: "Cables y Adaptadores", href: "/accesorios/cables-y-adaptadores" },
      { label: "Protectores de pantalla", href: "/accesorios/protectores-de-pantalla" },
      { label: "Teclados Mouse y Pencil", href: "/accesorios/teclados-mouse-y-pencil" },
      { label: "Bolsos y Mochilas", href: "/accesorios/bolsos-y-mochilas" },
      { label: "Fundas y Cobertores", href: "/accesorios/fundas-y-cobertores" },
      { label: "Correa Apple Watch", href: "/accesorios/correa-apple-watch" },
      { label: "Gaming", href: "/accesorios/gaming" },
      { label: "Otros", href: "/accesorios/otros" },
    ],
  },
  { label: "Outlet", href: "/outlet" },
  {
    label: "Promociones",
    href: "/promo",
    children: [
      { label: "Promo! Aguinaldo", href: "/promo-aginaldo" },
      { label: "Descuentos! Mundial", href: "/promo/mundial" },
      { label: "Ofertas BOMBA", href: "/etiqueta/ofertas-bomba" },
      { label: "Ahorra en Outlet", href: "/outlet" },
      { label: "Hasta 24 cuotas", href: "/etiqueta/hasta-24-cuotas" },
      { label: "Hasta 18 cuotas", href: "/etiqueta/hasta-18-cuotas" },
      { label: "Hasta 12 cuotas", href: "/etiqueta/hasta-12-cuotas" },
    ],
  },
  { label: "Servicio Técnico", href: "/servicio-tecnico" },
  { label: "Empresas", href: "/empresas" },
];
